---
- hosts: localhost
  connection: local

  vars_files:
    - config.yml

  pre_tasks:
    - name: "change security"
      command: spctl --master-disable
      become: yes

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers

  roles:
    - role: geerlingguy.mas
      when: mas_installed_apps

    - role: geerlingguy.homebrew
      when: homebrew_installed_packages

    - role: geerlingguy.dotfiles
      when: configure_dotfiles

  tasks:
    - import_tasks: tasks/osx.yml
      when: configure_osx

    - import_tasks: tasks/extra.yml
      when: configure_extra

    - import_tasks: tasks/zsh.yml
      when: configure_zsh

    - import_tasks: tasks/docks.yml
      when: configure_dock

    - name: Reboot
      command: reboot
      become: yes
