---
- name: Load git config
  command: git config --global core.excludesfile ~/.gitignore

- name: Create directory for Project
  file:
    path: "{{ project_dir }}/script"
    state: directory

- name: "SCRIPT |Â Install upgrade script"
  copy:
    src: "files/upgrade.sh"
    dest: "{{ project_dir }}/upgrade.sh"
    mode: 0755

- name: "SCRIPT | Add in crontab"
  cron:
    name: "upgrade"
    minute: "10"
    hour: "12"
    job: "sh {{ project_dir }}/upgrade.sh > /dev/null"
    state: present

- name: "ZSH | Download"
  git:
    repo: "git://github.com/robbyrussell/oh-my-zsh.git"
    dest: "~/.oh-my-zsh"

#- name: "ZSH | Download theme"
#  get_url: https://raw.githubusercontent.com/denysdovhan/spaceship-zsh-theme/master/install.zsh
#    dest: "/tmp/spaceship/"

#- name: "ZSH | Install theme"
#  script: /tmp/spaceship/install.zsh

- name: "ZSH | Download plugins zsh-completions"
  git:
    repo: "git://github.com/zsh-users/zsh-completions"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-completions/"

- name: "ZSH | Download plugins zsh-syntax-highlighting"
  git:
    repo: "git://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/"

- name: "ZSH | Copy config"
  template:
    src: "templates/zshrc.j2"
    dest: "~/.zshrc"

- name: "ZSH | Define default shell"
  command: "chsh -s /bin/zsh"
